steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/appengine-go:1.11
      - 1.11/jessie
    id: '1.11'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/appengine-go:1.11-slim
      - 1.11/slim
    id: '1.11-slim'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/appengine-go:1.11', 'gcr.io/$PROJECT_ID/appengine-go:latest']
    wait_for: ['1.11']
    id: 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/appengine-go:1.11-slim', 'gcr.io/$PROJECT_ID/appengine-go:slim']
    wait_for: ['1.11-slim']
    id: 'slim'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/appengine-go:1.11-alpine', 'gcr.io/$PROJECT_ID/appengine-go:alpine']
    wait_for: ['1.11-alpine']
    id: 'alpine'

images:
  - gcr.io/$PROJECT_ID/appengine-go:latest
  - gcr.io/$PROJECT_ID/appengine-go:slim
  - gcr.io/$PROJECT_ID/appengine-go:1.11
  - gcr.io/$PROJECT_ID/appengine-go:1.11-slim
  - gcr.io/$PROJECT_ID/appengine-go:1.11-alpine

timeout: '20m'
